### ISSUE TITLE
HN Feed Parsing Bugs

### ISSUE THREAD

**Issue by zshannon** [TosinAF/thenews#7]
Hey, you may have noticed that the HN feed is not rendering properly. They made changes to their HTML structure that broke libHN. I've sent libHN a [PR](https://github.com/bennyguitar/libHN/pull/26) that brings it to `v3.0.2`. Will want to update and push a build ASAP after libHN accepts that merge.

**Comment by TosinAF** [comment]
I've updated the libHN pod, submitting to the app store now. Cheers !
